<?php
/*
* This file is generated by Antigravity but will not be executed via artisan migrate
* unless PHP is available in the environment.
* The user should run this manually if needed.
*/

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('tbl_bundle_products', function (Blueprint $table) {
            if (!Schema::hasColumn('tbl_bundle_products', 'quantity')) {
                $table->integer('quantity')->default(1)->after('product_id');
            }
            if (!Schema::hasColumn('tbl_bundle_products', 'product_variant_id')) {
                $table->unsignedBigInteger('product_variant_id')->nullable()->after('quantity');
            }
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('tbl_bundle_products', function (Blueprint $table) {
            $table->dropColumn(['quantity', 'product_variant_id']);
        });
    }
};
